name: Java CI with Maven

# 1. Define quando o pipeline vai rodar (Sempre que abrir ou atualizar um PR)
on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    # Rodar em um servidor Ubuntu atualizado
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixar o código do seu repositório para o servidor do GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Instalar o Java
      - name: Set up JDK 25
        uses: actions/actions-setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      # Passo 3: Compilar o código e rodar todos os testes automatizados
      - name: Build and Test with Maven
        run: mvn clean test